# Practice Tensor


##  scaler , vector , matrices , tensor

In [34]:
import numpy as np

scalar = np.array(5)
print("scalar : " , scalar , "shape : " , scalar.shape , "dimension : " , scalar.ndim)

vector = np.array([1 , 2, 3 , 4])
print("vector : " ,  vector , "shape : " , vector.shape , "dimension : " , vector.ndim)

matrices = np.array([[1 , 2 , 3, 4],[5 , 6 , 7 , 8]])
print("matrices : " ,  matrices , "shape : " , matrices.shape , "dimension : " , matrices.ndim)

tensor = np.random.rand(2 ,3 ,4) 
print("tensor : " ,  tensor , "shape : " , tensor.shape , "dimension : " , tensor.ndim)

# tensor4D = np.random.rand(2 , 3 , 4 , 5) ## mainly used in images
# print("tensor4D : " ,  tensor4D , "shape : " , tensor4D.shape , "dimension : " , tensor4D.ndim)

## 5D tensor used in videos


scalar :  5 shape :  () dimension :  0
vector :  [1 2 3 4] shape :  (4,) dimension :  1
matrices :  [[1 2 3 4]
 [5 6 7 8]] shape :  (2, 4) dimension :  2
tensor :  [[[0.72628499 0.93696938 0.81140762 0.13375336]
  [0.42814135 0.20097483 0.52318995 0.05396153]
  [0.11931469 0.54102191 0.28876928 0.22819815]]

 [[0.29032907 0.48454652 0.09392677 0.68261311]
  [0.97062087 0.2576838  0.23914387 0.83811177]
  [0.99119957 0.32507342 0.65581858 0.33844384]]] shape :  (2, 3, 4) dimension :  3


## Basic Tensor Operation

In [11]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

print("Add:\n", a+b)
print("Subtract:\n", a-b)
print("Element-wise multiply:\n", a*b)
print("Matrix multiply:\n", a @ b)


Add:
 [[ 6  8]
 [10 12]]
Subtract:
 [[-4 -4]
 [-4 -4]]
Element-wise multiply:
 [[ 5 12]
 [21 32]]
Matrix multiply:
 [[19 22]
 [43 50]]


## Reshape & Manipulate Tensors

In [24]:
arr = np.arange(12).reshape(3 , 4)
print('array : ' , arr)

transpose = arr.T;
print('transpose : ' , transpose)

# Adding/removing dimensions
# print('squeeze : ' , arr.squeeze().shape)

y = np.random.rand(2 , 3, 4)

print(np.expand_dims(y , axis = 0).shape)
print(y)

print('squeeze : ' , y.squeeze().shape)
print(y)


array :  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
transpose :  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
(1, 2, 3, 4)
[[[0.87589419 0.08334132 0.64300283 0.92103427]
  [0.74556904 0.13084024 0.19587781 0.33914378]
  [0.25102952 0.5120361  0.25272784 0.83416426]]

 [[0.91730264 0.40737657 0.11185064 0.86194196]
  [0.11350437 0.24069069 0.59863197 0.13141162]
  [0.97637516 0.92401802 0.51480678 0.75032612]]]
squeeze :  (2, 3, 4)
[[[0.87589419 0.08334132 0.64300283 0.92103427]
  [0.74556904 0.13084024 0.19587781 0.33914378]
  [0.25102952 0.5120361  0.25272784 0.83416426]]

 [[0.91730264 0.40737657 0.11185064 0.86194196]
  [0.11350437 0.24069069 0.59863197 0.13141162]
  [0.97637516 0.92401802 0.51480678 0.75032612]]]


## Indexing and Slicing

In [31]:
arr = np.random.rand(2 , 3 , 4)
print(arr)

print('slicing : ' , arr[:,1:,3:])

[[[0.1737199  0.08489021 0.55007405 0.54236219]
  [0.16380848 0.3405647  0.83965038 0.94200523]
  [0.26276289 0.69860132 0.88776283 0.09807046]]

 [[0.3707135  0.49211532 0.15398015 0.90259718]
  [0.87121502 0.99080595 0.96603079 0.44769894]
  [0.5257945  0.97426681 0.44263722 0.73218305]]]
slicing :  [[[0.94200523]
  [0.09807046]]

 [[0.44769894]
  [0.73218305]]]


## Real ML Related Tasks

#### 1️⃣ One-hot encoding

In [35]:
labels = np.array([0,2,1,2])
one_hot = np.zeros((labels.size, labels.max()+1))
one_hot[np.arange(labels.size), labels] = 1
print(one_hot)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 2️⃣ Normalization

In [37]:
data = np.array([1 , 2, 3 , 4 , 5] , dtype = float)
normalized = ((data - data.mean())) / data.std()
print(normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


#### 3️⃣ Mini-batch creation

In [39]:
dataset = np.arange(20).reshape(10,2)  
batch_size = 3
for i in range(0, len(dataset), batch_size):
    print("Batch:\n", dataset[i:i+batch_size])

Batch:
 [[0 1]
 [2 3]
 [4 5]]
Batch:
 [[ 6  7]
 [ 8  9]
 [10 11]]
Batch:
 [[12 13]
 [14 15]
 [16 17]]
Batch:
 [[18 19]]
